#include "app/cli_args.h"

#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include "shared/core/build_config.h"
#include "test_util.h"

int main() {
    using V = std::vector<std::string>;
    const V launcher = {"app",   "/wp/dir", "-r",        "DP-4",         "-f",
                        "60",    "-s",      "--scaling", "fill",         "--clamp",
                        "clamp", "--layer", "bottom",    "--assets-dir", "/engine/assets"};
    CHECK(cli_args::positional(launcher) == "/wp/dir");
    std::string value;
    CHECK(cli_args::optionValue(launcher, {"-f", "--fps"}, value) && value == "60");
    CHECK(cli_args::optionValue(launcher, {"--assets-dir"}, value) && value == "/engine/assets");
    CHECK(cli_args::optionValue(launcher, {"-r", "--screen-root"}, value) && value == "DP-4");
    CHECK(cli_args::hasFlag(launcher, {"-s", "--silent"}));
    CHECK(!cli_args::hasFlag(launcher, {"--mute"}));

    const V trailing = {"app", "--fps=30", "--assets-dir=/a", "/wp"};
    CHECK(cli_args::positional(trailing) == "/wp");
    CHECK(cli_args::optionValue(trailing, {"--fps"}, value) && value == "30");

    const V optionsOnly = {"app", "--no-ui", "--gpu", "1"};
    CHECK(cli_args::positional(optionsOnly).empty());
    CHECK(!cli_args::optionValue(optionsOnly, {"--assets-dir"}, value));

    const V keyValue = {"app", "pkg=/x.pkg", "/wp"};
    CHECK(cli_args::positional(keyValue) == "/wp");

    const V layerDebug = {"app", "--layer-size", "320x180", "--layer-anchor", "top-left", "/wp"};
    CHECK(cli_args::positional(layerDebug) == "/wp");
    CHECK(cli_args::optionValue(layerDebug, {"--layer-size"}, value) && value == "320x180");

    const V diagnose = {"app", "--diagnose", "--diagnose-frame", "10", "/wp"};
    CHECK(cli_args::positional(diagnose) == "/wp");
    CHECK(cli_args::optionValue(diagnose, {"--diagnose-frame"}, value) && value == "10");

    const V setProps = {"app", "--set-property", "a=1", "--set-property", "b=two words", "--set-property=c=3", "/wp"};
    CHECK(cli_args::positional(setProps) == "/wp");
    const std::vector<std::string> properties = cli_args::optionValues(setProps, {"--set-property"});
    CHECK(properties.size() == 3);
    CHECK(properties[0] == "a=1");
    CHECK(properties[1] == "b=two words");
    CHECK(properties[2] == "c=3");
    CHECK(cli_args::optionValues(launcher, {"--set-property"}).empty());

    const V transition = {"app", "--transition", "crt", "--transition-duration", "500", "/wp"};
    CHECK(cli_args::positional(transition) == "/wp");
    CHECK(cli_args::optionValue(transition, {"--transition"}, value) && value == "crt");
    CHECK(cli_args::optionValue(transition, {"--transition-duration"}, value) && value == "500");

    const V mode = {"app", "--transition-mode", "freeze", "/wp"};
    CHECK(cli_args::positional(mode) == "/wp");
    CHECK(cli_args::optionValue(mode, {"--transition-mode"}, value) && value == "freeze");
    CHECK(cli_args::takesValue("--transition-mode"));

    const V devtools = {"app", "--web-devtools", "--web-devtools-port", "9333", "--web-devtools-browser", "chromium --app", "/wp"};
    CHECK(cli_args::positional(devtools) == "/wp");
    CHECK(cli_args::hasFlag(devtools, {"--web-devtools"}));
    CHECK(cli_args::optionValue(devtools, {"--web-devtools-port"}, value) && value == "9333");
    CHECK(cli_args::takesValue("--web-devtools-port"));
    CHECK(cli_args::optionValue(devtools, {"--web-devtools-browser"}, value) && value == "chromium --app");
    CHECK(cli_args::takesValue("--web-devtools-browser"));

    // Value detection comes from the same tables the help is built from.
    CHECK(cli_args::takesValue("--fps"));
    CHECK(cli_args::takesValue("--web-transport"));
    CHECK(cli_args::takesValue("--volume"));
    CHECK(cli_args::takesValue("--layer-size"));  // value option even in release
    CHECK(!cli_args::takesValue("--no-audio"));
    CHECK(!cli_args::takesValue("--cover"));
    CHECK(!cli_args::takesValue("--web-devtools"));

    // Help is generated by looping the groups, not written out again.
    char* help_buffer = nullptr;
    size_t help_size = 0;
    FILE* help_stream = open_memstream(&help_buffer, &help_size);
    CHECK(help_stream != nullptr);
    cli_args::printHelp(help_stream);
    fclose(help_stream);
    const std::string help(help_buffer, help_size);
    free(help_buffer);

    CHECK(help.find("Wallpaper:") != std::string::npos);
    CHECK(help.find("Graphics:") != std::string::npos);
    CHECK(help.find("Display:") != std::string::npos);
    CHECK(help.find("Transition:") != std::string::npos);
    CHECK(help.find("Control:") != std::string::npos);
    CHECK(help.find("Audio:") != std::string::npos);
    CHECK(help.find("Web:") != std::string::npos);
    CHECK(help.find("Particles:") != std::string::npos);
    CHECK(help.find("--web-transport") != std::string::npos);
    CHECK(help.find("--fps") != std::string::npos);
#if DEBUG_BUILD
    CHECK(help.find("Diagnostics:") != std::string::npos);
    CHECK(help.find("--diagnose") != std::string::npos);
#else
    CHECK(help.find("Diagnostics:") == std::string::npos);
    CHECK(help.find("--diagnose") == std::string::npos);
#endif

    return test::finish("cli args checks");
}
